name: 'Milo'
description: 'Runs Milo on the passed folder'
author: "Antonio Pagano"
inputs:
  folder:
    description: "Folder to review with Milo"
    default: "."
  version:
    description: "Version of milo to use"
    default: "latest"
runs:
  using: "composite"
  steps:
    - id: install_milo
      run: |
        export URL = https://github.com/wawandco/milo/releases/download/${{inputs.version}}/milo_Linux_x86_64.tar.gz
        if [${{inputs.version}}="latest"]; then 
          URL = "https://github.com/wawandco/milo/releases/latest/download/milo_Linux_x86_64.tar.gz"
        fi
        
        wget $URL
        tar -xzf milo_Linux_x86_64.tar.gz
        sudo mv milo /usr/local/bin/milo
      shell: bash
    
    - id: run_milo
      run: |
        milo review "${{inputs.folder}}"
      shell: bash