name: 'Milo'
description: 'Runs Milo on the passed folder'
author: "Antonio Pagano"
inputs:
  folder:
    description: "Folder to review with Milo"
    default: "."
  version:
    description: "Version of milo to use"
    default: "v0.6.0"
runs:
  using: "composite"
  steps:
    - id: install_milo
      run: |
        wget https://github.com/wawandco/milo/releases/download/${{inputs.version}}/milo_Linux_x86_64.tar.gz
        tar -xvzf milo_Linux_x86_64.tar.gz
        sudo mv milo /usr/local/bin/milo
      shell: bash
    
    - id: run_milo
      run: |
        milo review "${{inputs.folder}}"
      shell: bash