name: 'Milo'
description: 'Runs Milo on the passed folder'
author: "Antonio Pagano"
inputs:
  folder:
    description: "Folder to review with Milo"
    default: "."
runs:
  using: "composite"
  steps:
    - id: install_milo
      run: |
        wget https://github.com/wawandco/milo/releases/download/v0.6.0/milo_0.6.0_Linux_x86_64.tar.gz
        tar -xvzf milo_0.6.0_Linux_x86_64.tar.gz
        sudo mv milo /usr/local/bin/milo
      shell: bash
    
    - id: run_milo
      run: |
        echo "Running `milo review  ${{inputs.folder}}`"
        milo review "${{inputs.folder}}"
      shell: bash