name: 'Milo'
description: 'Runs Milo on the passed folder'
inputs:
  folder:
    default: "."
runs:
  using: "composite"
  steps:
    - id: install_go
      uses: actions/setup-go@v3
      with:
        go-version: "1.18.x"

    - id: install_milo
      run: go install "github.com/wawandco/milo/cmd/milo@v0.6.0"
      shell: bash
    
    - id: run_milo
      env:
        folder: ${{inputs.folder}}
      run: |
        echo "Running `milo review ${folder}`"
        milo review "${folder}"
      shell: bash