name: 'Milo'
description: 'Runs Milo on the passed folder'
author: "Antonio Pagano"
inputs:
  folder:
    description: "Folder to review with Milo"
    default: "."
runs:
  using: "composite"
  steps:
    - id: install_milo
      run: |
        curl -sf https://gobinaries.com/wawandco/milo/cmd/milo | sh
      shell: bash
    
    - id: run_milo
      run: |
        echo "Running `milo review  ${{inputs.folder}}`"
        milo review "${{inputs.folder}}"
      shell: bash