name: 'Milo'
description: 'Runs Milo on the passed folder'
runs:
  using: "composite"
  steps:
    - id: install_go
      uses: actions/setup-go@v3
      with:
        go-version: "1.18.x"

    - id: install_milo
      run: go install "github.com/wawandco/milo/cmd/milo@v0.6.0"
      shell: bash
    
    - id: run_milo
      run: |
        milo review ./...
      shell: bash