name: 'Milo'
description: 'Runs milo on the passed folder'
outputs:
  result:
    description: "Command output"
    value: ${{ steps.run_milo.outputs.result }}
runs:
  using: "composite"
  steps:
    - id: install_go
      uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: "1.18.x"
    
    - id: run_milo
      working-directory: .
      run: |
        go install "github.com/wawandco/milo/cmd/milo@v0.6.0"
        
        $(go env GOPATH)/bin/milo review ./...
        
        echo "Success!!"
        exit 0
      shell: bash