name: 'Milo'
description: 'Runs milo on the passed folder'
runs:
  using: "composite"
  steps:
    - id: install_go
      uses: actions/setup-go@v3
      with:
        go-version: "1.18.x"
    
    - id: run_milo
      working-directory: .
      run: |
        go install "github.com/wawandco/milo/cmd/milo@v0.6.0"
        
        echo "$(milo review ./...)"
        exit 0
      shell: bash